config/routes.rb
GoalingApp::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create, :show, :index]
  root :to => "users#index"
  resources :goals do
    resources :cheers, :only => [:create]
  end
  resources :cheers, :only => [:index]
  resources :comments, :only => [:create]
end

app/models/cheer.rb
# == Schema Information
#
# Table name: cheers
#
#  id         :integer          not null, primary key
#  giver_id   :integer
#  goal_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Cheer < ActiveRecord::Base
  CHEER_LIMIT = 12
  validates :giver_id, :goal_id, presence: true
  validates :goal_id, uniqueness: { scope: :giver_id }

  belongs_to :giver, class_name: "User"
  belongs_to :goal
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :text
#  author_id        :integer
#  commentable_id   :integer
#  commentable_type :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  private    :boolean          default(FALSE)
#  details    :text
#  completed  :boolean          default(FALSE)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Goal < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 6 }
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :user_id
  )
  has_many :cheers

  include Commentable
  # **NB**: comments association is created in Commentable
  # concern
  # has_many :comments, as: :commentable

  def cheered_by?(user)
    cheers.exists?(giver_id: user.id)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  password_digest :string(255)
#  session_token   :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  cheer_count     :integer
#

require 'bcrypt'

class User < ActiveRecord::Base
  include Commentable
  # **NB**: comments association is created in Commentable
  # concern
  # has_many :comments, as: :commentable

  attr_reader :password

  validates :session_token, presence: true
  validates :username, uniqueness: true, presence: true
  validates :password, length: { in: 6..12, allow_nil: true }
  validates :password_digest, presence: { message: "Password can't be blank." }
  validates :cheer_count, numericality: { only_integer: true, minimum: 0 }

  before_validation :ensure_session_token
  before_validation :ensure_cheer_count

  has_many :goals, :class_name => "Goal", :foreign_key => "user_id"
  has_many :cheers_given, :class_name => "Cheer", :foreign_key => "giver_id"
  has_many :cheers_received, :through => :goals, :source => :cheers

  def self.find_by_credentials(username, password)
    user_by_un = User.find_by_username(username)
    return nil unless user_by_un
    user_by_un.is_password?(password) ? user_by_un : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(32)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def decrement_cheer_count!
    self.cheer_count = self.cheer_count - 1
    self.save!
  end

  def is_password?(maybe_password)
    BCrypt::Password.new(self.password_digest).is_password?(maybe_password)
  end

  def password=(new_pw)
    @password = new_pw
    self.password_digest = BCrypt::Password.create(new_pw)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def ensure_cheer_count
    self.cheer_count ||= Cheer::CHEER_LIMIT
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :current_user_name, :current_user_id

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def current_user_id
    current_user ? current_user.id : nil
  end

  def current_user_name
    current_user ? current_user.username : nil
  end

  # before filters

  def require_current_user!
    redirect_to new_user_url unless current_user
  end

  def require_no_current_user!
    redirect_to root_url if current_user
  end
end

app/controllers/cheers_controller.rb
class CheersController < ApplicationController
  before_filter :require_current_user!

  def create
    redirect_to(:back) if current_user.cheer_count <= 0

    @cheer = Cheer.new(giver_id: current_user.id,
    goal_id: params[:goal_id])
    if @cheer.save
      current_user.decrement_cheer_count!
      raise "went over cheer limit" if current_user.cheer_count < 0
      goal_owner_name = Goal.find(params[:goal_id]).author.username
      flash[:notices] = ["You cheered #{goal_owner_name}'s goal!"]
      redirect_to(:back)
    else
      flash[:notices] = @cheer.errors.full_messages
      redirect_to(:back)
    end
  end

  def index
    @cheers = current_user.cheers_received
  end

  private

  def cheer_params
    params.require(:cheer).permit(:giver_id, :goal_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      flash[:errors] = ["Comment saved!"]
    else
      flash[:errors] = @comment.errors.full_messages
    end
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :body)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :require_current_user!

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      flash[:notices] = ["Goal saved!"]
      redirect_to goal_url(@goal)
    else
      flash[:notices] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      flash[:notices] = ["Goal updated!"]
      if request.referer == edit_goal_url(@goal)
        redirect_to @goal
      else
        redirect_to request.referer
      end
    else
      flash[:notices] = @goal.errors.full_messages
      render :edit
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def index
    @goals = current_user.goals
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    flash[:notices] = ["Goal deleted!"]
    redirect_to goals_url
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :details, :private, :completed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_current_user!, :only => [:destroy]
  before_filter :require_no_current_user!, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    credentials = [params[:user][:username], params[:user][:password]]
    @user = User.find_by_credentials(*credentials)
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:notices] = ["Invalid credentials."]
      @user = User.new
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_current_user!, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:notices] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/views/cheers/index.html.erb
<h1>My Cheers</h1>

<% @cheers.each do |cheer| %>
  <table>
    <tr>
      <th>Cheer given by:</th>
    </tr>
    <tr>
      <td><%= cheer.giver.username %></td>
    </tr>
    <tr>
      <th>For goal of:</th>
    </tr>
    <tr>
      <td><%= cheer.goal.title %></td>
    </tr>
  </table>
  <br />
<% end %>

app/views/goals/_goal_form.html.erb
<% action = (action_type == :new) ? goals_url : goal_url(goal) %>
<% button_text = (action_type == :new) ? "New Goal" : "Update Goal"%>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if action_type == :edit %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>

  <label>Title:
    <input type="text" value="<%= goal.title %>" name="goal[title]">
  </label>
  <br>

  <label>Details:
    <textarea name="goal[details]"><%= goal.details %></textarea>
  </label>
  <br>

  <label>Private?
    <input type="checkbox" name="goal[private]"
      <%= 'checked="true"' if goal.private %>>
  </label>
  <br>

  <label>Completed?
    <input type="checkbox" name="goal[completed]"
      <%= 'checked="true"' if goal.private %>>
  </label>
  <br>

  <input type="submit" value="<%= button_text %>">
</form>

app/views/goals/edit.html.erb
<h2>Edit Goal</h2>

<%= render "goal_form", action_type: :edit, goal: @goal %>

app/views/goals/index.html.erb
<h1>Your Goals</h1>
<ul>
  <% @goals.each do |goal| %>
    <%= render "shared/show_goal_basics", goal: goal %>
  <% end %>
</ul>

app/views/goals/new.html.erb
<h2>New Goal</h2>
<%= render "goal_form", action_type: :new, goal: @goal %>

app/views/goals/show.html.erb
<h2>Goal:</h2>

<table>
  <tr>
    <th>Title:</th>
    <td><%= @goal.title %></td>
  </tr>
  <tr>
    <th>Details:</th>
    <td><%= @goal.details %></td>
  </tr>
  <tr>
    <th>Visibility:</th>
    <td>
      <% if @goal.private %>
        Private
      <% else %>
        Public
      <% end %>
    </td>
  </tr>
  <tr>
    <th>Finished?:</th>
    <td>
      <% if @goal.completed %>
        Completed
      <% else %>
        Ongoing
      <% end %>
    </td>
  </tr>
  <tr>
    <th>Cheers:</th>
    <td><%= @goal.cheers.length %></td>
  </tr>
  <% if current_user && current_user.id == @goal.user_id %>
    <tr>
      <th>Completed?</th>
      <td>
        <%= render "shared/goal_complete_button", goal: @goal %>
      </td>
    </tr>
  <% end %>
</table>

<% @goal.comments.each do |comment| %>
  <p><%= comment.body %></p>
<% end %>
<%= render "shared/comments_form", commentable_id: @goal.id, commentable_type: "Goal" %>
<!-- add link to author's profile page later. -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goal App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1>GOALING APP</h1>
  <% if flash[:notices] %>
    <div class="notices">
      <% flash[:notices].each do |msg| %>
        <p><b><%= msg %></b></p>
      <% end %>
    </div>
  <% end %>

  <div class="pull-right">
    <% if current_user %>
      <p>Welcome <%= current_user_name %></p>
      <%= button_to "Log Out", session_url, method: :delete %>

      <p>Cheers Remaining:
        <span id="cheer-limit"><%= current_user.cheer_count %></span>
      </p>
    <% else %>
      <p><%= link_to "Sign Up", new_user_url %></p>
      <p>or</p>
      <p><%= link_to "Log In", new_session_url %></p>
    <% end %>
  </div>
</header>

<%= yield %>

</body>
</html>

app/views/shared/_cheer_button.html.erb
<form action="<%= goal_cheers_url(goal) %>" method="POST">
  <input type="hidden" name="authenticity_token" 
    value="<%= form_authenticity_token %>">
  <input type="submit" value="Cheer!">
</form>

app/views/shared/_comments_form.html.erb
<h3>New Comment</h3>
<form action="<%= comments_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[commentable_id]" value="<%= commentable_id %>">
  <input type="hidden" name="comment[commentable_type]" value="<%= commentable_type %>">
  <label>Comment
    <textarea name="comment[body]"></textarea>
  </label>
  <input type="submit" value="Save Comment">
</form>

app/views/shared/_goal_complete_button.html.erb
<form action="<%= goal_url(goal)%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="goal[completed]" value="<%= !goal.completed %>">
  <input type="submit"
  <% if goal.completed %>
  value="Oops!  Did not complete."
  <% else %>
  value="Complete"
  <% end %>
  id="goal_<%= goal.id %>_completed">
</form>

app/views/shared/_show_goal_basics.html.erb
<% privacy = (goal.private) ? "private" : "public" %>
<% completedness = (goal.completed) ? "Complete" : "Ongoing"%>

<li>
  <%= link_to goal.title, goal_url(goal) %>
  <p><i><%= privacy %></i></p>
  <p><i><%= completedness %></i></p>
  <br>

  <% if current_user && current_user.id == goal.user_id %>
    <%= render "shared/goal_complete_button", goal: goal %>
    <br>
    <%= button_to "delete '#{goal.title}' goal", goal_url(goal), method: :delete %>
  <% elsif current_user && !(goal.cheered_by?(current_user)) && current_user.cheer_count > 0 %>
    <%= render "shared/cheer_button", goal: goal %>
  <% end %>
</li>

app/views/shared/_user_form.html.erb
<% action = (type == :newuser) ? users_url : session_url %>
<% button_text = (type == :newuser) ? "Sign Up" : "Log In" %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username:
    <input type="text" value="<%= @user.username %>" name="user[username]">
  </label>
  <br>

  <label>Password:
    <input type="password" value="<%= @user.password %>" name="user[password]">
  </label>
  <br>

  <input type="submit" value="<%= button_text %>">
</form>

app/views/users/index.html.erb
<h2>Users</h2>

<% @users.each do |user| %>
  <%= link_to user.username, user_url(user) %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up!</h2>

<%= render "shared/user_form", user: @user, type: :newuser %>

app/views/users/show.html.erb
<h2><%= @user.username.capitalize %>'s Profile</h2>

<% @user.comments.each do |comment| %>
  <p><%= comment.body %></p>
<% end %>

<%= render "shared/comments_form", commentable_id: @user.id, commentable_type: "User" %>

<h3><%= @user.username.capitalize %>'s Goals:</h3>

<% if @user == current_user %>
  <%= link_to "New Goal", new_goal_url %>
  <%= link_to "My Cheers!", cheers_url %>
<% end %>

<ul>
  <% @user.goals.each do |goal| %>
    <% if (current_user && current_user.id == @user.id) || !(goal.private) %>
      <%= render "shared/show_goal_basics", goal: goal %>
    <% end %>
  <% end %>
</ul>

<%= link_to "All Users", users_url %>